### ISSUE TITLE
.getURl for danbooru incorrect 

### ISSUE THREAD

**Issue by Doomsdayrs** [Kodehawa/imageboard-api#10]
Example outputted

> https://danbooru.donmai.ushttps//danbooru.donmai.us/data/5ee26e50a8e4668849aafcf31d2a6c21.jpg

Which seems to stem from the geturl in its class.
```
    public String getParsedFileUrl() {
        return "https://danbooru.donmai.us" + file_url;
```
It seems this could be fixed if the first part of the file_url had it's https//danbooru.donmai.us removed.

**Comment by natanbc** [comment]
@Kodehawa fixpls im getting 400:embed:image

~~:^)~~
