### ISSUE TITLE
"Random images" isnt really random

### ISSUE THREAD

**Issue by DeadShinigami** [Kodehawa/imageboard-api#116]
Ive noticed that when grabbing images from danbooru, whether that be by using an asynchronous call or through creating ImageBoard object, the images it generates arent randomizing everytime. When printing out the image, its always the same image. If a span of time passes, however, there is a chance that this image changes from what it was. When printing out this new image however, it simply keeps printing out this same, new image. Is there a way to randomize the images everytime?

**Comment by Kodehawa** [comment]
The phrasing is incorrect on my side. They're not "randomized", I meant random as in just whatever the site returns. 

You'd need to fetch 100 images (or however many you want) and pick a random one yourself.
