### ISSUE TITLE
NoClassDefFound Error on build Jar

### ISSUE THREAD

**Issue by RinDoesJava** [Kodehawa/imageboard-api#16]
I really like this api, it's simple to use, and works perfectly when I run it through IntelliJ.
Once I build the Jar however, the API breaks and the class "DefaultImageBoards" is just gone.

**Comment by Kodehawa** [comment]
You're not shading the dependencies properly.

**Comment by RinDoesJava** [comment]
Ohh alright, I'm pretty new to this, so sorry about that, I'll have to see how to do it correctly
