### ISSUE TITLE
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException.

### ISSUE THREAD

**Issue by ShindouMihou** [Kodehawa/imageboard-api#22]
As the title says, I received an error on console when trying to fetch images, though they don't really have much impact on performance or haven't caused any issues to my Discord bot as far as I can tell, I wonder if I wrote something wrong here.

Here is the error message.
`Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
        at net.kodehawa.lib.imageboards.requests.RequestAction$1.onFailure(RequestAction.java:104)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)`

And here is the code I am using.
` public static void konachan(String tag) {

 // Async Getter       DefaultImageBoards.KONACHAN.search(50, tag).async(images -> {
            for (BoardImage image : images){
            // Check if image is SFW.
                if (image.getRating() == Rating.SAFE) {
                    // Stores URL in a list to be                         fetched later.
                    urls.add(image.getURL());
                }
            }
        });`

Is it a problem on my side, or something else...?

**Comment by ShindouMihou** [comment]
Changed up some code, and added a ifListIsEmpty void. It seems to fix it.

**Comment by Kodehawa** [comment]
This is what I use:
```
                api.search(list, finalRating).async(requestedImages -> {
                    // Account for this, somehow this happens sometimes.
                    if (isListNull(requestedImages, ctx))
                        return;

                    try {
                        // There should be no need for searches to contain loli content anyway, if it's gonna get locked away.
                        // This is more of a quality-of-life improvement, don't make them search again if random happened
                        // to pick undesirable lewd content.
                        // This also gets away with the need to re-roll, unless they looked up a prohibited tag.
                        List<BoardImage> filter = requestedImages.stream()
                                .filter(img -> !containsMinorTags(img.getTags()))
                                .collect(Collectors.toList());

                        if (filter.isEmpty()) {
                            ctx.sendLocalized("commands.imageboard.no_images", EmoteReference.SAD);
                            return;
                        }

                        BoardImage image = filter.get(r.nextInt(filter.size()));
                        sendImage(ctx, imageboard, image, dbGuild);
                    } catch (Exception e) {
                        ctx.sendLocalized("commands.imageboard.no_results", EmoteReference.SAD);
                    }
                }, failure -> ctx.sendLocalized("commands.imageboard.error_tag", EmoteReference.SAD));
```
