### ISSUE TITLE
[Feature-Request] Tag Search

### ISSUE THREAD

**Issue by Vodes** [Kodehawa/imageboard-api#36]
Would it be possible to search for tags on certain boards?
Maybe parse tables like on https://danbooru.donmai.us/tags

**Comment by Kodehawa** [comment]
I'll give it a look.

**Comment by Kodehawa** [comment]
This is a bit late, but this might be even simpler as Danbooru seems to provide an API for it: https://danbooru.donmai.us/wiki_pages/api%3Atags, with the parameters `fuzzy_name_matches` and `name_matches` it's possible to search through them.
