### ISSUE TITLE
Missing Artifact

### ISSUE THREAD

**Issue by EthanBuckton** [Kodehawa/imageboard-api#7]
I’m using jcenrer (bintray), and when trying to add imageboard-api to my Pom.xml I get 
“Missing artifact net.kodehawa:imageboard-api:jar:2.0.3_2”

**Comment by Kodehawa** [comment]
Did you add the bintray maven repo? somehow jcenter doesn't work properly for this :((

**Comment by EthanBuckton** [comment]
Via settings.xml?

**Comment by Kodehawa** [comment]
I actually have no idea how to do it on maven, that's why I just left the maven repository url (unlike on the Gradle where I added the repository on the example)

I'm pretty sure you actually add it on the pom.xml though

**Comment by EthanBuckton** [comment]
I’ve managed to resolve the issue, with extreme work-arounds on jcenter. Thank you for your help.

**Comment by Kodehawa** [comment]
I still don't know why jcenter gives me that many issues. This repo is published on the public jcenter but there's no way in hell it finds it on jcenter alone :(
