### ISSUE TITLE
Random image.

### ISSUE THREAD

**Issue by EthanBuckton** [Kodehawa/imageboard-api#8]
Sorry to be a nuisance, but I'm just struggling with the random image. When I call on it it returns with the same image every time. May seem dumb, but I have no idea why.

**Comment by EthanBuckton** [comment]
I figured out what the issue is: it get's the first image from the first page. It only changes when the page reloads or the bot reloads. What I don't know is how to fix it.

**Comment by Kodehawa** [comment]
Oh. Yeah, what I do is get let's say 45 images from a tag and then pick random from there

**Comment by Kodehawa** [comment]
You can actually choose the page to randomize it even further, no need for a tag either

**Comment by EthanBuckton** [comment]
Oh okay, thank you! I'll try that!

**Comment by EthanBuckton** [comment]
Sorry about this, but how would one go about doing that?

**Comment by EthanBuckton** [comment]
Haha I'm quite new to this, sorry.

**Comment by Kodehawa** [comment]
No need to say sorry lol, I'mma link an example once I get home

**Comment by EthanBuckton** [comment]
Alright, thanks for all the help!

**Comment by Kodehawa** [comment]
https://github.com/Mantaro/MantaroBot/blob/4.9/src/main/java/net/kodehawa/mantarobot/commands/image/ImageboardUtils.java#L182

**Comment by EthanBuckton** [comment]
I don't believe I quite understand it.

**Comment by Kodehawa** [comment]
I use a GET request with a random page between 1 and 100 and a query then I filter them by rating (do i already filter them by rate on the GET? lol) and then pick a random one.

Would be smth like this for you.
```java
                api.get(page, rating).async(requestedImages -> {
                    try {
                        int number = r.nextInt(requestedImages .size());
                        BoardImage image = requestedImages .get(number);
                        String tags = image.getTags().stream().collect(Collectors.joining(", "));
                        imageEmbed(languageContext, image.getURL(), String.valueOf(image.getWidth()), String.valueOf(image.getHeight()), tags, image.getRating(), imageboard, channel);
                    } catch(Exception e) { //handle internal exception }
                }, failure -> //handle external exception);
```

**Comment by EthanBuckton** [comment]
Oh alright! Thank you so much for this haha.

**Comment by EthanBuckton** [comment]
Sorry again, I'm so bad at this haha. I'm just a little confused about "ImageBoard<> api"?

**Comment by EthanBuckton** [comment]
Nevermind! Thank you for all of your help! I couldn't have done it without you! Seriously, thank you so so so much!
