### ISSUE TITLE
Gelbooru has switched to a new rating system

### ISSUE THREAD

**Issue by gemdude46** [Kodehawa/imageboard-api#82]
Gelbooru recently updated their ratings to have 4 values (general, sensitive, questionable, explicit) instead of the previous 3.

This means there is no way of searching for general or sensitive images there.

**Comment by Kodehawa** [comment]
Fixed in library by merit of version 2.5.2, commit https://github.com/Kodehawa/imageboard-api/commit/bedece0903137736740d33f80d5bf30ffcc38e79
