### ISSUE TITLE
Image searching with out of bounds exception

### ISSUE THREAD

**Issue by Doomsdayrs** [Kodehawa/imageboard-api#9]
Whenever i am searching up an tag, lets say the tag has 20 images. The method I'm currently using uses an Random generator to select between 1 and 100. Is there a way to get a random image without having to use a generator? 

Here's the code i'm currently using. 
```
int generation = gen.nextInt(100)+1;
		R34image = DefaultImageBoards.RULE34.search(100, combined ).blocking().get(generation);
    	
    	String output = R34image.getTags() + "\n **Rating:** " + R34image.getScore() + "\n **Size**: " + R34image.getWidth() + "x" + R34image.getHeight() + "\n" + R34image.getURL();
        
    	channel.sendMessage("__Image Search for:__ **"+combined+ "** \n" + output);
```

**Comment by Doomsdayrs** [comment]
It would be very useful to have something along the lines of `DefaultImageBoards.RULE34.search(100, combined ).blocking().getRandom(); `or something along those lines to randomly choose an image from the search results.

**Comment by Doomsdayrs** [comment]
The problem with what i'm implementing currently often runs into a nullpointerexception, since certain tags don't have as many images, sometimes they only have 5 or so, sometimes they have a thousand. 

This leaves an issue that if i set a random generator to 100, and the tag that is searched up only has 5 images. I only have a 5% chance of getting an image. Set it too high and too likely to pull up a null, set it too low and it is more likely to just loop individual images. 

A .getRandom() method would be getting the number of images from the search result, applying that as the limit to a random# generator, and sending back a random image using that generator. 

Currently i'm unaware if there even is a method to get the int of images from a search result.

**Comment by Doomsdayrs** [comment]
I never really thought of it that way, And it solves all the problems!
Thank you for taking your time with me

**Comment by Kodehawa** [comment]
No problem!
